sudo: required

services:
    - docker

env:
    - BUILD="docker-compose up -d"
    - BUILD="docker run -d --name db mattermost/mattermost-prod-db && sleep 5 && docker run -d --link db -p 80:80 --name app mattermost/mattermost-prod-app"

before_install:
    - docker-compose -f docker-compose-build.yml build

install:
    - eval $BUILD
    - sleep 10

script:
    - curl -sSf http://localhost > /dev/null

after_failure:
    - timeout 3s docker-compose logs app db web
